CREATE TABLE Atizapani.Usuarios(Id_Usuario INT AUTO_INCREMENT NOT NULL , NomUser VARCHAR(55) NOT NULL, ApUser VARCHAR(55) NOT NULL, 
AmUser VARCHAR(55) NOT NULL, TelefonoUser VARCHAR(10) NOT NULL, EmailUser VARCHAR(255) NOT NULL , Password VARCHAR(255) NOT NULL , 
Id_Tuser INT NOT NULL, PRIMARY key(Id_Usuario))ENGINE = INNODB; 